import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useNavigate } from "react-router-dom";
import {
  Sparkles, Send, CheckCircle, Linkedin, Instagram, Twitter,
  ChevronRight, RotateCcw, ThumbsUp, ThumbsDown, Edit3,
  Zap, Target, Users, BarChart2, Clock, Globe, ArrowLeft
} from "lucide-react";

// ── Page transition variants ──────────────────────────────────────────────────
const pageVariants = {
  enter: (dir) => ({
    x: dir > 0 ? "60%" : "-60%",
    opacity: 0,
    filter: "blur(8px)",
  }),
  center: {
    x: 0,
    opacity: 1,
    filter: "blur(0px)",
    transition: { duration: 0.5, ease: [0.22, 1, 0.36, 1] },
  },
  exit: (dir) => ({
    x: dir > 0 ? "-60%" : "60%",
    opacity: 0,
    filter: "blur(8px)",
    transition: { duration: 0.35, ease: [0.22, 1, 0.36, 1] },
  }),
};

// ── Helpers ───────────────────────────────────────────────────────────────────
const PLATFORMS = [
  { id: "linkedin", label: "LinkedIn", icon: Linkedin, color: "#0a66c2", bg: "rgba(10,102,194,0.12)", border: "rgba(10,102,194,0.35)" },
  { id: "instagram", label: "Instagram", icon: Instagram, color: "#e1306c", bg: "rgba(225,48,108,0.12)", border: "rgba(225,48,108,0.35)" },
  { id: "twitter", label: "Twitter / X", icon: Twitter, color: "#1d9bf0", bg: "rgba(29,155,240,0.12)", border: "rgba(29,155,240,0.35)" },
];

const TONES = ["Professional", "Casual", "Bold", "Inspirational", "Educational"];
const AUDIENCES = ["B2B Decision Makers", "Students", "General Public", "Industry Professionals", "Job Seekers"];
const CAMPAIGNS = ["Brand Awareness", "Lead Generation", "Event Promotion", "Product Launch", "Recruitment"];

const GENERATED_POSTS = {
  linkedin: {
    copy: `🚀 The future of marketing isn't hiring more people — it's working smarter.

We just processed 3 months of campaign data in under 30 seconds. Our AI identified that Tuesday 9am posts drive 47% more engagement for B2B audiences in the APAC region.

That insight used to take a team of analysts a week to surface.

The shift isn't coming. It's already here.

How is your team adapting to AI-driven marketing?

#MarketingAI #B2BMarketing #DigitalTransformation #AITools`,
    hashtags: ["#MarketingAI", "#B2BMarketing", "#DigitalTransformation", "#AITools"],
    emoji: "💼",
    engagement: { reach: "12.4K", impressions: "38.2K", ctr: "4.7%" },
  },
  instagram: {
    copy: `Your competitors are already using AI to write, schedule & optimise their content ✨

Are you still doing it manually?

Drop a 🔥 if you're ready to automate your marketing.

#MarketingAutomation #AIMarketing #ContentCreator #DigitalMarketing #GrowthHacking`,
    hashtags: ["#MarketingAutomation", "#AIMarketing", "#ContentCreator", "#DigitalMarketing"],
    emoji: "📸",
    engagement: { reach: "28.1K", impressions: "91.5K", ctr: "6.2%" },
  },
  twitter: {
    copy: `Hot take: 80% of your marketing content could be AI-generated by end of 2025.

The other 20%? That's the human edge — strategy, empathy, creativity.

The brands that figure out this ratio first will dominate their niches.

Thoughts? 🧵`,
    hashtags: ["#MarketingAI", "#ContentStrategy", "#FutureOfMarketing"],
    emoji: "🐦",
    engagement: { reach: "8.9K", impressions: "22.3K", ctr: "3.8%" },
  },
};

// ── Step indicator ────────────────────────────────────────────────────────────
const StepIndicator = ({ current }) => {
  const steps = ["Prompt", "Generate", "Publish"];
  return (
    <div className="flex items-center justify-center gap-0 mb-10">
      {steps.map((s, i) => {
        const done = i < current;
        const active = i === current;
        return (
          <React.Fragment key={s}>
            <div className="flex flex-col items-center gap-1.5">
              <motion.div
                className="w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold font-mono"
                animate={{
                  background: done
                    ? "linear-gradient(135deg,#00f5ff,#7c3aed)"
                    : active
                    ? "rgba(0,245,255,0.15)"
                    : "rgba(255,255,255,0.04)",
                  border: done
                    ? "1.5px solid transparent"
                    : active
                    ? "1.5px solid rgba(0,245,255,0.6)"
                    : "1.5px solid rgba(255,255,255,0.1)",
                  color: done ? "#04050d" : active ? "#00f5ff" : "#475569",
                  boxShadow: active ? "0 0 14px rgba(0,245,255,0.35)" : "none",
                }}
                transition={{ duration: 0.4 }}
              >
                {done ? <CheckCircle size={16} /> : i + 1}
              </motion.div>
              <span
                className="text-xs font-mono tracking-widest uppercase"
                style={{
                  color: active ? "#00f5ff" : done ? "#a78bfa" : "#334155",
                  transition: "color 0.3s",
                }}
              >
                {s}
              </span>
            </div>
            {i < steps.length - 1 && (
              <div
                className="w-16 md:w-24 h-px mx-2 mb-5"
                style={{
                  background: done
                    ? "linear-gradient(90deg,#00f5ff,#7c3aed)"
                    : "rgba(255,255,255,0.08)",
                  transition: "background 0.5s",
                }}
              />
            )}
          </React.Fragment>
        );
      })}
    </div>
  );
};

// ── Step 1 — Prompt ───────────────────────────────────────────────────────────
const PromptStep = ({ onNext }) => {
  const [prompt, setPrompt] = useState("");
  const [platform, setPlatform] = useState("linkedin");
  const [tone, setTone] = useState("Professional");
  const [audience, setAudience] = useState("B2B Decision Makers");
  const [campaign, setCampaign] = useState("Brand Awareness");

  const placeholders = [
    "Create 3 posts about AI marketing for APAC region...",
    "Write a LinkedIn post about our new product launch...",
    "Generate Instagram content for March intake campaign...",
  ];
  const [phIdx] = useState(Math.floor(Math.random() * placeholders.length));

  const canProceed = prompt.trim().length > 0 || true; // always allow for demo

  return (
    <motion.div
      className="w-full max-w-2xl mx-auto"
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
    >
      {/* Header */}
      <div className="text-center mb-8">
        <div
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-mono mb-4"
          style={{ background: "rgba(0,245,255,0.08)", border: "1px solid rgba(0,245,255,0.25)", color: "#00f5ff" }}
        >
          <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
          STEP 1 — BRIEF YOUR AI
        </div>
        <h2 className="text-3xl md:text-4xl font-bold mb-3" style={{ color: "#f1f5f9" }}>
          What do you want to{" "}
          <span
            style={{
              background: "linear-gradient(135deg,#00f5ff,#7c3aed)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              backgroundClip: "text",
            }}
          >
            create?
          </span>
        </h2>
        <p className="text-slate-400 text-sm">
          Describe your campaign in plain English — or use the guided fields below.
        </p>
      </div>

      {/* Plain English input */}
      <div
        className="rounded-2xl p-1 mb-5"
        style={{ background: "linear-gradient(135deg,rgba(0,245,255,0.2),rgba(124,58,237,0.2))" }}
      >
        <div className="rounded-xl p-4" style={{ background: "#070910" }}>
          <div className="flex items-start gap-3">
            <div
              className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5"
              style={{ background: "rgba(0,245,255,0.1)", border: "1px solid rgba(0,245,255,0.25)" }}
            >
              <Sparkles size={14} style={{ color: "#00f5ff" }} />
            </div>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder={placeholders[phIdx]}
              rows={3}
              className="flex-1 bg-transparent resize-none text-sm text-slate-200 placeholder-slate-600 outline-none leading-relaxed"
            />
          </div>
        </div>
      </div>

      {/* Platform select */}
      <div className="mb-5">
        <label className="block text-xs font-mono text-slate-500 uppercase tracking-widest mb-2">Platform</label>
        <div className="flex gap-3 flex-wrap">
          {PLATFORMS.map((p) => (
            <button
              key={p.id}
              onClick={() => setPlatform(p.id)}
              className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all"
              style={{
                background: platform === p.id ? p.bg : "rgba(255,255,255,0.03)",
                border: `1px solid ${platform === p.id ? p.border : "rgba(255,255,255,0.08)"}`,
                color: platform === p.id ? p.color : "#475569",
                boxShadow: platform === p.id ? `0 0 16px ${p.bg}` : "none",
              }}
            >
              <p.icon size={15} />
              {p.label}
            </button>
          ))}
        </div>
      </div>

      {/* Guided fields */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
        {[
          { label: "Tone", value: tone, setter: setTone, options: TONES },
          { label: "Audience", value: audience, setter: setAudience, options: AUDIENCES },
          { label: "Campaign Goal", value: campaign, setter: setCampaign, options: CAMPAIGNS },
        ].map(({ label, value, setter, options }) => (
          <div key={label}>
            <label className="block text-xs font-mono text-slate-500 uppercase tracking-widest mb-2">{label}</label>
            <select
              value={value}
              onChange={(e) => setter(e.target.value)}
              className="w-full text-sm rounded-xl px-3 py-2.5 outline-none appearance-none cursor-pointer"
              style={{
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(255,255,255,0.1)",
                color: "#e2e8f0",
              }}
            >
              {options.map((o) => (
                <option key={o} value={o} style={{ background: "#070910" }}>
                  {o}
                </option>
              ))}
            </select>
          </div>
        ))}
      </div>

      {/* CTA */}
      <button
        onClick={() => onNext({ prompt, platform, tone, audience, campaign })}
        className="w-full py-4 rounded-2xl text-base font-bold flex items-center justify-center gap-2 transition-all"
        style={{
          background: "linear-gradient(135deg,rgba(0,245,255,0.15),rgba(124,58,237,0.25))",
          border: "1.5px solid rgba(0,245,255,0.4)",
          color: "#ffffff",
          boxShadow: "0 0 30px rgba(0,245,255,0.15)",
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.boxShadow = "0 0 50px rgba(0,245,255,0.3)";
          e.currentTarget.style.transform = "translateY(-2px)";
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.boxShadow = "0 0 30px rgba(0,245,255,0.15)";
          e.currentTarget.style.transform = "translateY(0)";
        }}
      >
        <Zap size={18} style={{ color: "#00f5ff" }} />
        Generate with AI
        <ChevronRight size={18} />
      </button>
    </motion.div>
  );
};

// ── Step 2 — Generate ─────────────────────────────────────────────────────────
const GenerateStep = ({ config, onNext, onBack }) => {
  const [phase, setPhase] = useState("loading"); // loading | preview
  const [displayedText, setDisplayedText] = useState("");
  const [approved, setApproved] = useState(null);

  const post = GENERATED_POSTS[config.platform] || GENERATED_POSTS.linkedin;
  const platformInfo = PLATFORMS.find((p) => p.id === config.platform);

  // Typewriter effect
  useEffect(() => {
    if (phase !== "preview") return;
    let i = 0;
    const full = post.copy;
    setDisplayedText("");
    const timer = setInterval(() => {
      i++;
      setDisplayedText(full.slice(0, i));
      if (i >= full.length) clearInterval(timer);
    }, 12);
    return () => clearInterval(timer);
  }, [phase, post.copy]);

  // Fake loading sequence
  useEffect(() => {
    const t = setTimeout(() => setPhase("preview"), 2800);
    return () => clearTimeout(t);
  }, []);

  const loadingSteps = [
    { label: "Fetching brand guidelines", icon: Target, delay: 0 },
    { label: "Analysing campaign context", icon: BarChart2, delay: 0.6 },
    { label: "Running RAG on historical data", icon: Clock, delay: 1.2 },
    { label: "Generating platform-optimised copy", icon: Globe, delay: 1.8 },
  ];

  return (
    <motion.div
      className="w-full max-w-2xl mx-auto"
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      {/* Header */}
      <div className="text-center mb-8">
        <div
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-mono mb-4"
          style={{ background: "rgba(124,58,237,0.1)", border: "1px solid rgba(124,58,237,0.3)", color: "#a78bfa" }}
        >
          <span className="w-1.5 h-1.5 rounded-full bg-purple-400 animate-pulse" />
          STEP 2 — AI GENERATION
        </div>
        <h2 className="text-3xl md:text-4xl font-bold mb-3" style={{ color: "#f1f5f9" }}>
          {phase === "loading" ? (
            <>AI is <span style={{ background: "linear-gradient(135deg,#a78bfa,#00f5ff)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>thinking...</span></>
          ) : (
            <>Your content is <span style={{ background: "linear-gradient(135deg,#00ff88,#00f5ff)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>ready</span></>
          )}
        </h2>
      </div>

      <AnimatePresence mode="wait">
        {phase === "loading" ? (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="rounded-2xl p-6 space-y-4"
            style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)" }}
          >
            {/* Central spinner */}
            <div className="flex justify-center mb-6">
              <div className="relative w-20 h-20">
                <motion.div
                  className="absolute inset-0 rounded-full"
                  style={{ border: "2px solid rgba(0,245,255,0.15)" }}
                />
                <motion.div
                  className="absolute inset-0 rounded-full"
                  style={{ border: "2px solid transparent", borderTopColor: "#00f5ff" }}
                  animate={{ rotate: 360 }}
                  transition={{ duration: 1.2, repeat: Infinity, ease: "linear" }}
                />
                <motion.div
                  className="absolute inset-2 rounded-full"
                  style={{ border: "2px solid transparent", borderTopColor: "#7c3aed" }}
                  animate={{ rotate: -360 }}
                  transition={{ duration: 1.8, repeat: Infinity, ease: "linear" }}
                />
                <div className="absolute inset-0 flex items-center justify-center">
                  <Sparkles size={22} style={{ color: "#00f5ff" }} />
                </div>
              </div>
            </div>

            {loadingSteps.map(({ label, icon: Icon, delay }) => (
              <motion.div
                key={label}
                initial={{ opacity: 0, x: -12 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay, duration: 0.4 }}
                className="flex items-center gap-3"
              >
                <div
                  className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                  style={{ background: "rgba(0,245,255,0.08)", border: "1px solid rgba(0,245,255,0.2)" }}
                >
                  <Icon size={13} style={{ color: "#00f5ff" }} />
                </div>
                <span className="text-sm text-slate-400 font-mono">{label}</span>
                <motion.div
                  className="flex-1 h-px"
                  initial={{ scaleX: 0, originX: 0 }}
                  animate={{ scaleX: 1 }}
                  transition={{ delay: delay + 0.2, duration: 0.6 }}
                  style={{ background: "linear-gradient(90deg,rgba(0,245,255,0.3),transparent)" }}
                />
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: delay + 0.8 }}>
                  <CheckCircle size={14} style={{ color: "#00ff88" }} />
                </motion.div>
              </motion.div>
            ))}
          </motion.div>
        ) : (
          <motion.div key="preview" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            {/* Platform badge */}
            <div className="flex items-center gap-2 mb-4">
              <div
                className="flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-mono"
                style={{ background: platformInfo?.bg, border: `1px solid ${platformInfo?.border}`, color: platformInfo?.color }}
              >
                {platformInfo && <platformInfo.icon size={12} />}
                {platformInfo?.label} Post
              </div>
              <div
                className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-full text-xs font-mono"
                style={{ background: "rgba(0,255,136,0.08)", border: "1px solid rgba(0,255,136,0.2)", color: "#00ff88" }}
              >
                <span className="w-1.5 h-1.5 rounded-full bg-green-400" />
                AI Generated
              </div>
            </div>

            {/* Post card */}
            <div
              className="rounded-2xl p-5 mb-5"
              style={{
                background: "rgba(255,255,255,0.02)",
                border: `1px solid ${platformInfo?.border || "rgba(255,255,255,0.1)"}`,
                boxShadow: `0 0 30px ${platformInfo?.bg || "transparent"}`,
              }}
            >
              {/* Mock profile */}
              <div className="flex items-center gap-3 mb-4">
                <div
                  className="w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm"
                  style={{ background: "linear-gradient(135deg,#00f5ff,#7c3aed)", color: "#04050d" }}
                >
                  H
                </div>
                <div>
                  <div className="text-sm font-semibold text-slate-200">SingSinghAI</div>
                  <div className="text-xs text-slate-500">AI-Powered Marketing Agency</div>
                </div>
              </div>

              <pre
                className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap typewriter-cursor font-sans"
                style={{ fontFamily: "inherit" }}
              >
                {displayedText}
              </pre>

              {/* Engagement preview */}
              <div
                className="flex items-center gap-4 mt-4 pt-4"
                style={{ borderTop: "1px solid rgba(255,255,255,0.06)" }}
              >
                {Object.entries(post.engagement).map(([k, v]) => (
                  <div key={k} className="flex items-center gap-1.5">
                    <span className="text-xs font-mono font-bold" style={{ color: "#00f5ff" }}>{v}</span>
                    <span className="text-xs text-slate-600 capitalize">{k}</span>
                  </div>
                ))}
                <span className="text-xs text-slate-600 ml-auto">Projected</span>
              </div>
            </div>

            {/* Review actions */}
            <div className="grid grid-cols-3 gap-3 mb-6">
              {[
                { label: "Approve", icon: ThumbsUp, color: "#00ff88", bg: "rgba(0,255,136,0.1)", border: "rgba(0,255,136,0.3)", action: "approve" },
                { label: "Edit", icon: Edit3, color: "#00f5ff", bg: "rgba(0,245,255,0.08)", border: "rgba(0,245,255,0.25)", action: "edit" },
                { label: "Reject", icon: ThumbsDown, color: "#ff6b35", bg: "rgba(255,107,53,0.08)", border: "rgba(255,107,53,0.25)", action: "reject" },
              ].map(({ label, icon: Icon, color, bg, border, action }) => (
                <button
                  key={action}
                  onClick={() => { setApproved(action); if (action !== "reject") setTimeout(() => onNext({ post, config }), 600); }}
                  className="py-3 rounded-xl text-sm font-medium flex items-center justify-center gap-2 transition-all"
                  style={{
                    background: approved === action ? bg : "rgba(255,255,255,0.03)",
                    border: `1px solid ${approved === action ? border : "rgba(255,255,255,0.08)"}`,
                    color: approved === action ? color : "#475569",
                    boxShadow: approved === action ? `0 0 16px ${bg}` : "none",
                  }}
                >
                  <Icon size={14} />
                  {label}
                </button>
              ))}
            </div>

            <button
              onClick={onBack}
              className="w-full py-3 rounded-xl text-sm text-slate-500 flex items-center justify-center gap-2 transition-all hover:text-slate-300"
              style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)" }}
            >
              <RotateCcw size={13} />
              Regenerate with new brief
            </button>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

// ── Step 3 — Publish ──────────────────────────────────────────────────────────
const PublishStep = ({ config, onReset }) => {
  const [selected, setSelected] = useState([config.platform]);
  const [publishing, setPublishing] = useState(false);
  const [published, setPublished] = useState(false);
  const [progress, setProgress] = useState(0);

  const togglePlatform = (id) => {
    setSelected((prev) => prev.includes(id) ? prev.filter((p) => p !== id) : [...prev, id]);
  };

  const handlePublish = () => {
    setPublishing(true);
    let p = 0;
    const timer = setInterval(() => {
      p += 4;
      setProgress(p);
      if (p >= 100) {
        clearInterval(timer);
        setTimeout(() => { setPublishing(false); setPublished(true); }, 300);
      }
    }, 60);
  };

  const platformInfo = PLATFORMS.find((p) => p.id === config.platform);
  const post = GENERATED_POSTS[config.platform] || GENERATED_POSTS.linkedin;

  return (
    <motion.div
      className="w-full max-w-2xl mx-auto"
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      {/* Header */}
      <div className="text-center mb-8">
        <div
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-mono mb-4"
          style={{ background: "rgba(0,255,136,0.08)", border: "1px solid rgba(0,255,136,0.25)", color: "#00ff88" }}
        >
          <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
          STEP 3 — PUBLISH
        </div>
        <h2 className="text-3xl md:text-4xl font-bold mb-3" style={{ color: "#f1f5f9" }}>
          {published ? (
            <>Content <span style={{ background: "linear-gradient(135deg,#00ff88,#00f5ff)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>published!</span></>
          ) : (
            <>Ready to <span style={{ background: "linear-gradient(135deg,#00ff88,#7c3aed)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>go live?</span></>
          )}
        </h2>
        {!published && <p className="text-slate-400 text-sm">Select your platforms and push to the publishing queue.</p>}
      </div>

      <AnimatePresence mode="wait">
        {published ? (
          <motion.div
            key="success"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
            className="text-center"
          >
            {/* Success ring */}
            <div className="flex justify-center mb-8">
              <div className="relative w-28 h-28">
                <motion.div
                  className="absolute inset-0 rounded-full"
                  style={{ background: "rgba(0,255,136,0.08)", border: "2px solid rgba(0,255,136,0.4)" }}
                  animate={{ boxShadow: ["0 0 20px rgba(0,255,136,0.2)", "0 0 50px rgba(0,255,136,0.4)", "0 0 20px rgba(0,255,136,0.2)"] }}
                  transition={{ duration: 2, repeat: Infinity }}
                />
                <div className="absolute inset-0 flex items-center justify-center">
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
                  >
                    <CheckCircle size={48} style={{ color: "#00ff88" }} />
                  </motion.div>
                </div>
              </div>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-3 gap-4 mb-8">
              {[
                { label: "Platforms", value: selected.length, color: "#a78bfa", suffix: "" },
                { label: "Projected Reach", value: "40K+", color: "#00f5ff", suffix: "" },
                { label: "Est. Engagement", value: "5.2%", color: "#00ff88", suffix: "" },
              ].map(({ label, value, color }) => (
                <div
                  key={label}
                  className="rounded-xl p-4 text-center"
                  style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)" }}
                >
                  <div className="text-2xl font-bold font-mono mb-1" style={{ color }}>{value}</div>
                  <div className="text-xs text-slate-500">{label}</div>
                </div>
              ))}
            </div>

            {/* Published platforms */}
            <div className="flex justify-center gap-3 mb-8">
              {selected.map((id) => {
                const p = PLATFORMS.find((pl) => pl.id === id);
                if (!p) return null;
                return (
                  <div
                    key={id}
                    className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium"
                    style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.color }}
                  >
                    <p.icon size={14} />
                    {p.label}
                    <CheckCircle size={13} />
                  </div>
                );
              })}
            </div>

            {/* Analytics teaser */}
            <div
              className="rounded-2xl p-5 mb-6 text-left"
              style={{ background: "rgba(0,245,255,0.03)", border: "1px solid rgba(0,245,255,0.12)" }}
            >
              <div className="flex items-center gap-2 mb-3">
                <BarChart2 size={14} style={{ color: "#00f5ff" }} />
                <span className="text-xs font-mono text-slate-400 uppercase tracking-widest">Analytics Dashboard Preview</span>
              </div>
              <div className="space-y-3">
                {[
                  { label: "Reach", value: 72, color: "#00f5ff" },
                  { label: "Impressions", value: 88, color: "#7c3aed" },
                  { label: "CTR", value: 45, color: "#00ff88" },
                ].map(({ label, value, color }) => (
                  <div key={label}>
                    <div className="flex justify-between text-xs text-slate-500 mb-1">
                      <span>{label}</span><span style={{ color }} className="font-mono">{value}%</span>
                    </div>
                    <div className="h-1.5 rounded-full" style={{ background: "rgba(255,255,255,0.06)" }}>
                      <motion.div
                        className="h-full rounded-full"
                        initial={{ width: 0 }}
                        animate={{ width: `${value}%` }}
                        transition={{ duration: 1, delay: 0.5, ease: "easeOut" }}
                        style={{ background: `linear-gradient(90deg,${color},transparent)` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <button
              onClick={onReset}
              className="w-full py-4 rounded-2xl text-base font-bold flex items-center justify-center gap-2 transition-all"
              style={{
                background: "linear-gradient(135deg,rgba(0,245,255,0.12),rgba(124,58,237,0.2))",
                border: "1.5px solid rgba(0,245,255,0.35)",
                color: "#ffffff",
              }}
            >
              <RotateCcw size={16} />
              Create another campaign
            </button>
          </motion.div>
        ) : (
          <motion.div key="publish-form" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
            {/* Platform select */}
            <div className="mb-6">
              <label className="block text-xs font-mono text-slate-500 uppercase tracking-widest mb-3">
                Select platforms to publish to
              </label>
              <div className="flex gap-3 flex-wrap">
                {PLATFORMS.map((p) => (
                  <button
                    key={p.id}
                    onClick={() => togglePlatform(p.id)}
                    className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all"
                    style={{
                      background: selected.includes(p.id) ? p.bg : "rgba(255,255,255,0.03)",
                      border: `1px solid ${selected.includes(p.id) ? p.border : "rgba(255,255,255,0.08)"}`,
                      color: selected.includes(p.id) ? p.color : "#475569",
                      boxShadow: selected.includes(p.id) ? `0 0 16px ${p.bg}` : "none",
                    }}
                  >
                    <p.icon size={15} />
                    {p.label}
                    {selected.includes(p.id) && <CheckCircle size={13} />}
                  </button>
                ))}
              </div>
            </div>

            {/* Schedule option */}
            <div
              className="rounded-xl p-4 mb-6 flex items-center justify-between"
              style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)" }}
            >
              <div className="flex items-center gap-3">
                <Clock size={15} style={{ color: "#a78bfa" }} />
                <div>
                  <div className="text-sm text-slate-300 font-medium">Optimal posting time</div>
                  <div className="text-xs text-slate-500 font-mono">Tuesday 9:00 AM AEST — AI recommended</div>
                </div>
              </div>
              <div
                className="px-3 py-1.5 rounded-lg text-xs font-mono"
                style={{ background: "rgba(139,92,246,0.1)", border: "1px solid rgba(139,92,246,0.25)", color: "#a78bfa" }}
              >
                Schedule
              </div>
            </div>

            {/* Projected metrics */}
            <div className="grid grid-cols-3 gap-3 mb-6">
              {Object.entries(post.engagement).map(([k, v]) => (
                <div
                  key={k}
                  className="rounded-xl p-3 text-center"
                  style={{ background: "rgba(0,245,255,0.03)", border: "1px solid rgba(0,245,255,0.1)" }}
                >
                  <div className="text-lg font-bold font-mono mb-0.5" style={{ color: "#00f5ff" }}>{v}</div>
                  <div className="text-xs text-slate-500 capitalize">{k}</div>
                </div>
              ))}
            </div>

            {/* Publish button */}
            {publishing ? (
              <div>
                <div
                  className="rounded-xl p-4 mb-3"
                  style={{ background: "rgba(0,255,136,0.04)", border: "1px solid rgba(0,255,136,0.15)" }}
                >
                  <div className="flex items-center justify-between text-xs font-mono text-slate-400 mb-2">
                    <span>Publishing to {selected.join(", ")}...</span>
                    <span style={{ color: "#00ff88" }}>{progress}%</span>
                  </div>
                  <div className="h-1.5 rounded-full" style={{ background: "rgba(255,255,255,0.06)" }}>
                    <motion.div
                      className="h-full rounded-full"
                      style={{ width: `${progress}%`, background: "linear-gradient(90deg,#00f5ff,#00ff88)", transition: "width 0.1s linear" }}
                    />
                  </div>
                </div>
              </div>
            ) : (
              <button
                onClick={handlePublish}
                disabled={selected.length === 0}
                className="w-full py-4 rounded-2xl text-base font-bold flex items-center justify-center gap-2 transition-all"
                style={{
                  background: selected.length > 0
                    ? "linear-gradient(135deg,rgba(0,255,136,0.15),rgba(0,245,255,0.15))"
                    : "rgba(255,255,255,0.03)",
                  border: `1.5px solid ${selected.length > 0 ? "rgba(0,255,136,0.4)" : "rgba(255,255,255,0.06)"}`,
                  color: selected.length > 0 ? "#ffffff" : "#334155",
                  boxShadow: selected.length > 0 ? "0 0 30px rgba(0,255,136,0.15)" : "none",
                }}
              >
                <Send size={16} />
                Publish Now
              </button>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

// ── Main page ─────────────────────────────────────────────────────────────────
const MarketingDemoPage = () => {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [direction, setDirection] = useState(1);
  const [config, setConfig] = useState(null);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 40);
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const goTo = (next) => {
    setDirection(next > step ? 1 : -1);
    setStep(next);
  };

  const handlePromptNext = (data) => {
    setConfig(data);
    goTo(1);
  };

  const handleGenerateNext = (data) => {
    setConfig((prev) => ({ ...prev, ...data }));
    goTo(2);
  };

  const handleReset = () => {
    setConfig(null);
    setDirection(-1);
    setStep(0);
  };

  return (
    <div className="min-h-screen hud-grid" style={{ background: "#04050d", color: "#e2e8f0" }}>
      {/* Background blobs */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div
          className="radial-blob morphing-blob"
          style={{ width: 600, height: 600, top: "-10%", left: "-5%", background: "rgba(0,245,255,0.04)" }}
        />
        <div
          className="radial-blob morphing-blob"
          style={{ width: 500, height: 500, bottom: "-10%", right: "-5%", background: "rgba(124,58,237,0.05)", animationDelay: "7s" }}
        />
      </div>

      {/* Minimal navbar */}
      <header
        className="fixed top-0 left-0 right-0 z-50 transition-all duration-300"
        style={{
          background: scrolled ? "rgba(4,5,13,0.92)" : "rgba(4,5,13,0.4)",
          backdropFilter: "blur(16px)",
          WebkitBackdropFilter: "blur(16px)",
          borderBottom: scrolled ? "1px solid rgba(0,245,255,0.12)" : "1px solid transparent",
        }}
      >
        <div className="max-w-7xl mx-auto px-4 flex items-center justify-between h-16">
          <div className="flex items-center gap-3 cursor-pointer" onClick={() => navigate("/")}>
            <img src="/logo2.png" alt="SingSinghAI" className="w-9 h-9 rounded-lg object-contain" />
            <div>
              <div
                className="font-display font-bold text-lg leading-none"
                style={{
                  background: "linear-gradient(135deg,#00f5ff,#7c3aed)",
                  WebkitBackgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                  backgroundClip: "text",
                }}
              >
                SingSinghAI
              </div>
              <div className="font-mono text-xs" style={{ color: "rgba(0,245,255,0.5)" }}>
                Marketing Intelligence
              </div>
            </div>
          </div>

          <div
            className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-mono"
            style={{ background: "rgba(0,245,255,0.06)", border: "1px solid rgba(0,245,255,0.2)", color: "rgba(0,245,255,0.7)" }}
          >
            <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
            LIVE DEMO
          </div>

          <button
            onClick={() => navigate("/")}
            className="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors"
          >
            <ArrowLeft size={15} />
            <span className="hidden sm:inline">Back to site</span>
          </button>
        </div>
      </header>

      {/* Main */}
      <main className="relative z-10 min-h-screen flex flex-col items-center justify-center px-4 pt-28 pb-16">
        {/* Hero label */}
        <motion.div
          className="text-center mb-4"
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-lg font-mono text-slate-500 uppercase tracking-widest">
            Marketing GenAI — Interactive Demo
          </h1>
        </motion.div>

        <StepIndicator current={step} />

        {/* Page transition container */}
        <div className="w-full max-w-2xl overflow-hidden">
          <AnimatePresence mode="wait" custom={direction}>
            {step === 0 && (
              <motion.div
                key="step0"
                custom={direction}
                variants={pageVariants}
                initial="enter"
                animate="center"
                exit="exit"
              >
                <PromptStep onNext={handlePromptNext} />
              </motion.div>
            )}
            {step === 1 && (
              <motion.div
                key="step1"
                custom={direction}
                variants={pageVariants}
                initial="enter"
                animate="center"
                exit="exit"
              >
                <GenerateStep
                  config={config}
                  onNext={handleGenerateNext}
                  onBack={() => goTo(0)}
                />
              </motion.div>
            )}
            {step === 2 && (
              <motion.div
                key="step2"
                custom={direction}
                variants={pageVariants}
                initial="enter"
                animate="center"
                exit="exit"
              >
                <PublishStep config={config} onReset={handleReset} />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>
    </div>
  );
};

export default MarketingDemoPage;
